---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://github.com/sg-social/tango-secure/settings/hooks
sections:
- type: directory
  path: content/about
  label: About
  create: documents
  match: "**/*"
- type: directory
  path: content/technology
  label: Technology
  create: documents
  match: "**/*"
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
- type: heading
  label: Data
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/_index.md"
  templates:
  - author
- type: directory
  path: config/_default
  label: Config
  create: all
  match: "**/*"
  new_doc_ext: yaml
- type: directory
  path: content/post
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.75.1
