---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://github.com/sg-social/tango-secure/settings/hooks
sections:
- type: heading
  label: Content
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/technology
  label: Technology
  create: all
  match: "**/*"
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
- type: heading
  label: Site info
- type: directory
  path: config/_default
  label: Config
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: configt/menus
  label: Menus
  create: all
  match: "**/*"
  new_doc_ext: json
  templates:
  - menu-item
- type: directory
  path: config/footer
  label: Footer
  create: all
  match: "**/*"
  new_doc_ext: json
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.75.1
